version: '3.8'

services:
  backend:
    build: .
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/main.py
      FLASK_ENV: development
      MAIL_USERNAME: jheysonperezramirez6@gmail.com
      MAIL_PASSWORD: xwmkoucgsomjlmic
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      RABBITMQ_HOST: rabbitmq
      DATABASE_URL: postgresql://postgres:postgres@db/tienda
    depends_on:
      - rabbitmq
      - db
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tienda
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  boleta_consumer:
    build:
      context: .
    container_name: boleta_consumer
    command: ["python", "app/consumidores/boleta_consumer.py"]
    depends_on:
      - rabbitmq
    environment:
      MAIL_USERNAME: jheysonperezramirez6@gmail.com
      MAIL_PASSWORD: xwmkoucgsomjlmic
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      RABBITMQ_HOST: rabbitmq
    restart: always

  factura_consumer:
    build:
      context: .
    container_name: factura_consumer
    command: ["python", "app/consumidores/factura_consumer.py"]
    depends_on:
      - rabbitmq
    environment:
      MAIL_USERNAME: jheysonperezramirez6@gmail.com
      MAIL_PASSWORD: xwmkoucgsomjlmic
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      RABBITMQ_HOST: rabbitmq
    restart: always

volumes:
  pgdata:
